num_rounds : 3

query_analysis_prompt : |
  #任务
  query分析与增强：给定query『%s』，请你
  1. 判断这个query是通用query还是个性化query：如果query只包含城市、天数等信息（e.g., 北京三日游），则为通用query；如果query还包含其他信息（e.g., 景点类别、季节、节假日、旅游群体等），则为个性化query。
  2. 如果这个query是个性化query，请你根据自己的理解总结梳理这个query要求旅游攻略满足什么具体的个性化要求；如果这个query是通用query，回答“无”即可。

  #示例1: 输入query 『北京五日游』
  {"query类型":"通用","query要求":"无"}
  #示例2: 输入query 『南通春季自然风光五日游』
  {"query类型":"个性化","query要求":{"季节":"春季","景点类别":"自然风光"}}

  请用json格式回答：
  ```json
  {"query类型":"xxx（通用或个性化）","query要求":{"xx":"xxxx",...}}或{"query类型":"xxx（通用或个性化）","query要求":"无"}
  ```

generic_plan_init_prompt : |
  #任务
  旅游规划：给定景点列表和现成的可参考的规划方案，围绕『%s』这个query生成景点规划。
  
  #基本要求
  1. 文章结构按照行程天数展开，比如"第一天"、"第二天"和"第三天"。如果query没有要求，请根据景点列表和你的知识自行推理行程天数。
  2. 按计划访问时间顺序规划景点POI。景点POI从景点列表中选择，禁止选择列表之外的POI。
  3. 景点POI信息要求：
    - 为每个景点规划访问时间段，时间段包括"早晨，上午，中午，下午，傍晚，晚上"这6种，如果涉及多个时间段，中间用&连接，比如"上午&中午&下午"。
    - 并规划具体的游玩起止时间（24小时制几点到几点，比如“9:00-14:00”），不同POI的游玩时间禁止有重叠，要留出空档时间，每个POI规划的时间要连续，不允许用&分段连接。
    - 景点输出格式：{"名称":"xxx","时间段":"xxx(xx:xx-xx:xx)"}
  4. 请用json格式回答。

  #景点列表：
  %s

  #参考规划方案：
  %s

  #景点规划要求：
  1. 空间：考虑景点POI地理位置的聚集程度。请根据你的地理知识和POI的地址介绍，将地理位置相距较近的景点POI应分配到同一天内，地理位置相距较远的景点POI应分配到不同天。同一天景点之间禁止距离太远。
  2. 时间：
    - 每个POI必须要在开放时间访问，优先考虑景点的推荐开始游玩时间，并保证充足的游玩时长（参考景点的预计游玩时长）。
    - 每天的总行程时间不能过于紧凑，保证总行程时间不能过长、游玩的景点数量不能过多，保证除了景点游玩之外足够的空档时间（为食宿交通留出充足时间）。
  3. 景点语义：
    - 优先考虑热门的、城市特色的景点POI。
    - 保证景点POI类别多样性。

  请你从列表中选择景点并规划景点访问时间，以满足上述景点规划要求。你可以选择参考搜索结果中包含的现成POI规划方案，但请判断搜索内容中的规划是否合理、是否满足上述所有条件，需要你有选择地参考、归纳、借鉴，排除不相关或不合理的信息。
  最后用json格式回答。

  #示例
  ```json
  {"第一天":[{"名称":"xxx","时间段":"xxx(xx:xx-xx:xx)"},{"名称":"xxx","时间段":"xxx(xx:xx-xx:xx)"},...],"第二天":[{"名称":"xxx","时间段":"xxx(xx:xx-xx:xx)"},{"名称":"xxx","时间段":"xxx(xx:xx-xx:xx)"},...]}
  ```

personal_plan_init_prompt : |
  #任务
  旅游规划：给定景点列表和现成的可参考的规划方案，围绕『%s』这个query生成景点规划。
  
  #基本要求
  1. 文章结构按照行程天数展开，比如"第一天"、"第二天"和"第三天"。如果query没有要求，请根据景点列表和你的知识自行推理行程天数。
  2. 按计划访问时间顺序规划景点POI。景点POI从景点列表中选择，禁止选择列表之外的POI。
  3. 景点POI信息要求：
    - 为每个景点规划访问时间段，时间段包括"早晨，上午，中午，下午，傍晚，晚上"这6种，如果涉及多个时间段，中间用&连接，比如"上午&中午&下午"。
    - 并规划具体的游玩起止时间（24小时制几点到几点，比如“9:00-14:00”），不同POI的游玩时间禁止有重叠，要留出空档时间，每个POI规划的时间要连续，不允许用&分段连接。
    - 景点输出格式：{"名称":"xxx","时间段":"xxx(xx:xx-xx:xx)"}
  4. 请用json格式回答。

  #景点列表：
  %s

  #参考规划方案：
  %s

  #景点规划要求：
  1. 规划必须优先贴合query的要求：「%s」。
  2. 在满足query个性化要求的前提下：
    a. 空间：考虑景点POI地理位置的聚集程度。请根据你的地理知识和POI的地址介绍，将地理位置相距较近的景点POI应分配到同一天内，地理位置相距较远的景点POI应分配到不同天。同一天景点之间禁止距离太远。
    b. 时间：
      - 每个POI必须要在开放时间访问，优先考虑景点的推荐开始游玩时间，并保证充足的游玩时长（参考景点的预计游玩时长）。
      - 每天的总行程时间不能过于紧凑，保证总行程时间不能过长、游玩的景点数量不能过多，保证除了景点游玩之外足够的空档时间（为食宿交通留出充足时间）。
    c. 景点语义：
      - 优先考虑热门的、城市特色的景点POI。
      - 保证景点POI类别多样性。
  3. 有些个性化需求可能会和通用要求存在冲突，在这种情况下优先考虑个性化要求。
    - 比如query是“特种兵旅游”，则每天的行程总时间、景点游玩数量、空档时间、景点的游玩时长、游玩开始时间没有特别要求，整体行程可以紧凑一些。
    - 比如query要求和景点POI相关（e.g., “自然风光旅游”、“亲子游”、“秋游”、“春节旅游”等），则景点POI类别多样性没有特别要求，在满足query约束要求的POI中选择热门的景点。

  请你从列表中选择景点并规划景点访问时间，以满足上述景点规划要求。你可以选择参考搜索结果中包含的现成POI规划方案，但请判断搜索内容中的规划是否合理、是否满足上述所有条件，需要你有选择地参考、归纳、借鉴，排除不相关或不合理的信息。
  最后用json格式回答。

  #示例
  ```json
  {"第一天":[{"名称":"xxx","时间段":"xxx(xx:xx-xx:xx)"},{"名称":"xxx","时间段":"xxx(xx:xx-xx:xx)"},...],"第二天":[{"名称":"xxx","时间段":"xxx(xx:xx-xx:xx)"},{"名称":"xxx","时间段":"xxx(xx:xx-xx:xx)"},...]}
  ```

plan_evaluation_reflect_prompt : |
  #任务
  旅游规划：给定景点列表，围绕『%s』这个query生成景点规划。

  #景点列表：
  %s

  你之前已经生成了一批规划结果，并对它们做了评估：
  - 评估方式（优化目标）如下：
  %s
  - 规划结果如下（按最优性降序排列）：
  %s

  请你根据评估结果分析这些规划的差距，依据优化目标思考什么样的规划是好的、如何得到更优的规划。
  你之前已经有如下思考：
  %s

  下面请你完善你之前的思考（重复的就不用回答了），回答要精简（不超过500字），逐个优化目标分析，用json格式回答（只回答你的最终思考即可，不用回答分析过程）。

plan_crossover_mutation_prompt : |
  #任务
  旅游规划：给定景点列表，围绕『%s』这个query生成景点规划。

  #景点列表：
  %s

  请你从列表中选择景点并规划景点访问时间，以满足上述景点规划要求。

  你之前已经生成了一批规划结果，并对它们做了评估：
  - 评估方式（优化目标）如下：
  %s
  - 规划结果如下（按最优性降序排列）：
  %s

  根据评估结果你有如下思考：
  %s

  下面请你按照如下步骤生成新的规划
  1. 选择：从之前生成的规划结果中挑选两个相似程度较低的规划。
  2. 交叉：将这两个规划进行融合、加工，形成一个新的规划，兼具原先两个规划的优点。
  3. 变异：请根据你的思考，继续改进优化交叉后的新规划。
  请你迭代重复以上步骤，直至生成「%s」个新规划，这「%s」个新规划各不相同，且要和之前生成的规划均不重复，但是要比之前的规划结果更优。

  最后用json格式一并回答这「%s」个规划。（一定要保证生成规划的多样性、不重复性，不与之前的规划重复，且各个评估指标上更优。）
  #示例
  ```json
  [{"第一天":[{"名称":"xxx","时间段":"xxx(xx:xx-xx:xx)"},{"名称":"xxx","时间段":"xxx(xx:xx-xx:xx)"},...],"第二天":[{"名称":"xxx","时间段":"xxx(xx:xx-xx:xx)"},{"名称":"xxx","时间段":"xxx(xx:xx-xx:xx)"},...]},...]
  ```

plan_mutation_only_prompt : |
  #任务
  旅游规划：给定景点列表，围绕『%s』这个query生成景点规划。

  #景点列表：
  %s

  请你从列表中选择景点并规划景点访问时间，以满足上述景点规划要求。

  你之前已经生成了一批尚佳的规划结果，并对它们做了评估：
  - 评估方式（优化目标）如下：
  %s
  - 规划结果如下（按最优性降序排列）：
  %s

  根据评估结果你有如下思考：
  %s

  下面请根据你的思考，分别改进优化这批规划。改进后的「%s」个新规划各不相同，且要和之前生成的规划均不一样，但是要比之前的规划结果更优。

  最后用json格式一并回答这「%s」个规划（分别基于原先规划做改进）。（一定要保证生成规划的多样性、不重复性，不与之前的规划重复，且各个评估指标上更优。）
  #示例
  ```json
  [{"第一天":[{"名称":"xxx","时间段":"xxx(xx:xx-xx:xx)"},{"名称":"xxx","时间段":"xxx(xx:xx-xx:xx)"},...],"第二天":[{"名称":"xxx","时间段":"xxx(xx:xx-xx:xx)"},{"名称":"xxx","时间段":"xxx(xx:xx-xx:xx)"},...]},...]
  ```



# ---------------------------------------Baidu aiapi retriever----------------------------------------------#

temperature : 0

# dump_flag : true

map_api_keys : ['xxx']
