query_relevance_compare_prompt : |
  #角色
  你是一名旅游路线规划咨询师，对城市旅游相关的兴趣点（Point-of-interest，POI）有深入了解，对于行程规划有丰富经验，同时擅长撰写行程，语言风格简洁明了。
  
  #问题
  给定两组景点规划方案（按时间顺序排好的列表），比较哪一组方案的旅游规划和「%s」这个query相关性更高，并给出分析解释。

  #两份景点规划方案
  ---
  %s
  ---
  %s
  ---

  请用json格式回答哪个方案更好。只能回答两个字：“前者”或“后者”（如果你认为两个方案一样，回答“平局”），并给出具体的理由。

  #示例（请严格按照json语法回答，禁止在json回答内加注释）（请严格按照json语法回答，禁止在json加注释）
  ```json
  {"理由":"xxxxxx","评估结果":"xxx（前者、后者或平局）"}
  ```

poi_relevance_prompt : |
  #角色
  你是一名旅游路线规划咨询师，对城市旅游相关的兴趣点（Point-of-interest，POI）有深入了解，对于行程规划有丰富经验，同时擅长撰写行程，语言风格简洁明了。
  
  #问题
  给定「%s」这个query，分别判断选中的景点是否满足query要求，回答“满足”或“不满足”。

  #选中的景点
  %s

  请你简单地用文字解释时间不满足的景点POI的原因（满足的就不用解释了），并用json格式回答最终处理好的评估结果。
  #示例（请严格按照json语法回答，禁止在json回答内加注释）：
  ```json
  {"景点名称1":"满足","景点名称2":"不满足","景点名称3":"满足",...}
  ```

time_relevance_prompt : |
  #角色
  你是一名旅游路线规划咨询师，对城市旅游相关的兴趣点（Point-of-interest，POI）有深入了解，对于行程规划有丰富经验，同时擅长撰写行程，语言风格简洁明了。
  
  #问题
  给定「%s」这个query，分别判断景点的时间规划是否满足query要求，回答“满足”或“不满足”。

  #景点规划时间段列表（我们省略了景点名称，只保留了时间段信息）
  %s

  请你简单地用文字解释时间不满足的景点时间段的原因（满足的就不用解释了），并用json格式回答最终处理好的评估结果。
  #示例（请严格按照json语法回答，禁止在json回答内加注释）：
  ```json
  {"景点1":"满足","景点2":"不满足","景点3":"满足",...}
  ```

time_quality_prompt : |
  #角色
  你是一名旅游路线规划咨询师，对城市旅游相关的兴趣点（Point-of-interest，POI）有深入了解，对于行程规划有丰富经验，同时擅长撰写行程，语言风格简洁明了。
  
  #问题
  给定「%s」这个query和若干条景点的时间段规划结果，分别判断这些景点规划的时间段是否合理，回答“合适”或“不合适”。

  #景点时间规划
  %s

  请你简单地用文字解释时间不合适的景点POI的原因（合适的就不用解释了），并用json格式回答最终处理好的评估结果。
  #示例（请严格按照json语法回答，禁止在json回答内加注释）：
  ```json
  {"景点名称1":"合适","景点名称2":"不合适","景点名称3":"合适",...}
  ```

start_time_quality_prompt : |
  #角色
  你是一名旅游路线规划咨询师，对城市旅游相关的兴趣点（Point-of-interest，POI）有深入了解，对于行程规划有丰富经验，同时擅长撰写行程，语言风格简洁明了。
  
  #问题
  给定「%s」这个query和若干条景点游玩开始时间规划结果，分别判断这些景点规划的时间段是否合理，回答“合适”或“不合适”。

  #景点开始游玩时间规划结果
  %s

  请你简单地用文字解释时间不合适的景点POI的原因（合适的就不用解释了），并用json格式回答最终处理好的评估结果。
  #示例（请严格按照json语法回答，禁止在json回答内加注释）：
  ```json
  {"景点名称1":"合适","景点名称2":"不合适","景点名称3":"合适",...}

plan_quality_compare_prompt : |
  #角色
  你是一名旅游路线规划咨询师，对城市旅游相关的兴趣点（Point-of-interest，POI）有深入了解，对于行程规划有丰富经验，同时擅长撰写行程，语言风格简洁明了。
  
  #问题
  围绕「%s」这个query，给定两组景点规划方案（按时间顺序排好的列表），比较哪一组方案的旅游规划整体行程质量更高，并给出分析解释。

  #两份景点规划方案
  ---
  %s
  ---
  %s
  ---

  请用json格式回答哪个方案更好。只能回答两个字：“前者”或“后者”（如果你认为两个方案一样，回答“平局”），并给出具体的理由。

  #示例（请严格按照json语法回答，禁止在json回答内加注释）
  ```json
  {"理由":"xxxxxx","评估结果":"xxx（前者、后者或平局）"}
  ```

plan_objective_quality_compare_prompt : |
  #角色
  你是一名旅游路线规划咨询师，对城市旅游相关的兴趣点（Point-of-interest，POI）有深入了解，对于行程规划有丰富经验，同时擅长撰写行程，语言风格简洁明了。
  
  #问题
  围绕「%s」这个query，给定两组景点规划方案（按时间顺序排好的列表），依据具体的评估标准，比较哪一组方案的旅游规划整体行程质量更高，并给出分析解释。

  #评估标准
  a. 通用要求：
    1. 空间：考虑景点POI地理位置的聚集程度。请根据你的地理知识和POI的地址介绍，将地理位置相距较近的景点POI应分配到同一天内，地理位置相距较远的景点POI应分配到不同天。同一天景点之间禁止距离太远。
    2. 时间：
      - 每个POI必须要在开放时间访问，优先考虑景点的推荐开始游玩时间，并保证充足的游玩时长（参考景点的预计游玩时长）。
      - 一般情况下，每天的总行程时间不能过于紧凑，保证总行程时间不能过长、游玩的景点数量不能过多，保证除了景点游玩之外足够的空档时间（为食宿交通留出充足时间）。
    3. 景点语义：
      - 一般情况下，优先考虑热门的、城市特色的景点POI。
      - 一般情况下，保证景点POI类别多样性，比如自然风光、历史文化、休闲娱乐、艺术科技、城市观光、宗教文化等。
  b. 个性化要求：如果query存在额外的个性化约束要求，请理解、总结这些个性化要求，在选择景点POI和规划行程时充分考虑这些个性化要求。
    1. 有些个性化需求可能会和通用要求存在冲突，在这种情况下优先考虑个性化要求。
      - 比如query是“特种兵旅游”，则每天的行程总时间、景点游玩数量、空档时间、景点的游玩时长、游玩开始时间没有特别要求，整体行程可以紧凑一些。
      - 比如query要求和景点POI相关（e.g., “自然风光旅游”、“亲子游”、“秋游”、“春节旅游”等），则景点POI类别多样性没有特别要求，在满足query约束要求的POI中选择热门的景点。。

  #评估依据
  %s

  #两份景点规划方案
  ---
  %s
  ---
  %s
  ---

  请用json格式回答哪个方案更好（综合考虑所有评估标准）。只能回答两个字：“前者”或“后者”（如果你认为两个方案一样，回答“平局”），并给出具体的理由。

  #示例（请严格按照json语法回答，禁止在json回答内加注释）
  ```json
  {"理由":"xxxxxx","评估结果":"xxx（前者、后者或平局）"}
  ```

# ---------------------------------------Baidu aiapi retriever----------------------------------------------#

temperature : 0

map_api_keys : ['xxx']
