
# ------------------------------------------------Prompt------------------------------------------------#

base_url : http://127.0.0.1:6006/v1/
api_keys : ['xxx']

model : gpt-4o
temperature : 0.00001
top_p : 1
max_tokens : 4096
is_debug : True
